### ISSUE TITLE
playlist download error

### ISSUE THREAD

**Issue by aashna2331** [khansaad1275/Termux-YTD#11]
so basically i was just experimenting around.. n found that it is capable for playlist download.. and i came across a bug.. its basically like.. if that playlist contains a privated or deleted video the whole process would get stuck.. like it can't skip a particular vid or so.. can u fix that??  😅

**Comment by khansaad1275** [comment]
> so basically i was just experimenting around.. n found that it is capable for playlist download.. and i came across a bug.. its basically like.. if that playlist contains a privated or deleted video the whole process would get stuck.. like it can't skip a particular vid or so.. can u fix that?? 😅

Fixed the issue. Now you can download any playlist without interrupts.
