### ISSUE TITLE
Termux - YTD error

### ISSUE THREAD

**Issue by 6dmin** [khansaad1275/Termux-YTD#14]
![Screenshot_20210901-080228_Termux](https://user-images.githubusercontent.com/85904784/131614742-03c88a19-effe-4e86-93d8-e05f3db52e72.jpg)
Hallo, 
My download works fine but I'm getting an error before the downloads begin. Above is the attached screenshot. Kindly help. 
Thank.

**Comment by OakAtsume** [comment]
Hello there!
I have looked at your problem and it seems this is not an issue with the project but your system

"The .netrc file contains login and initialization information used by the auto-login process. It generally resides in the user’s home directory, but a location outside of the home directory can be set using the environment variable NETRC."
https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html

**Comment by 6dmin** [comment]
Thank you for your reply.
Ok. I did edit bash.bashrc so that I could customize termux welcome screen.
Could that be the reason I'm getting .netrc error and do I correct it while
maintaining my customised termux?

**Comment by OakAtsume** [comment]
bash.bashrc is the startup file for Bash/GNU shell for what I'm aware this file will not interact with  .netrc unless you modified it to do so.

**Comment by xandermamet** [comment]
In this case, .netrc is used by youtube-dl python script. It is necessary for proxy's auth, if you use it.
