### ISSUE TITLE
Use format list from video metada 

### ISSUE THREAD

**Issue by dvhh** [khansaad1275/Termux-YTD#17]
https://github.com/khansaad1275/Termux-YTD/blob/475b745ec68365f39c0db912f1ab49d302bc99e0/termux-url-opener#L21

A format list can be obtained via ` youtube-dl -F <URL>`, format identifier are fixed and can be matched to a internal list if needed or just list the raw list.

**Comment by khansaad1275** [comment]
> https://github.com/khansaad1275/Termux-YTD/blob/475b745ec68365f39c0db912f1ab49d302bc99e0/termux-url-opener#L21
> 
> A format list can be obtained via ` youtube-dl -F <URL>`, format identifier are fixed and can be matched to a internal list if needed or just list the raw list.

what do you exactly want? a list of all the codec available? won't it create more confusion for people who are beginner ?
