### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Matteodo016** [khansaad1275/Termux-YTD#19]
How to fix this sir

/data/data/com.termux/files/home/bin/termux-url-opener: line 51: youtube-dl: command not found

Thank you for you response

**Comment by khansaad1275** [comment]
> How to fix this sir
> 
> /data/data/com.termux/files/home/bin/termux-url-opener: line 51: youtube-dl: command not found
> 
> Thank you for you response

fixed ✅
