### ISSUE TITLE
Instillation Problem

### ISSUE THREAD

**Issue by Boomyofizz** [khansaad1275/Termux-YTD#21]
I attempted to use the compact instillation command presented, and Termux encountered a couple problems it seems. I only know the most basic parts of programming as of currently, so I'm just gonna share a screenshot rather than try to explain.
![Screenshot_20220726-024853-822](https://user-images.githubusercontent.com/53241794/180953139-f59e4695-50b1-4530-928a-44cfeeb04966.png)

I would like to have this great YouTube downloader work again. It's been too long since I had to download it and make it work.

**Comment by khansaad1275** [comment]
https://www.learntermux.tech/2022/01/Download-Termux-Latest-Version.html This is not a issue with tool, you just have to install the termux from different and not from the playstore.
