### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ricolytness** [khansaad1275/Termux-YTD#29]
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

👆👆👆👆👆👆 This is typical what it shows me everytime I try to download a video

**Comment by khansaad1275** [comment]
I think we have fixed this way back, I am closing this.
