### ISSUE TITLE
Is there a way to change the output of where the video is stored?

### ISSUE THREAD

**Issue by FawazBinSaleem** [khansaad1275/Termux-YTD#33]
I want the videos to directly show up in my gallery, is there a way to do that?

**Comment by MMT007** [comment]
- First
```nano .yt-dlp/config/config``` on Termux
- Second
then change ```-o ~/storage/shared/Youtube/%(title)s.%(ext)s``` to ```-o ~/storage/shared/DCIM/Camera/%(title)s.%(ext)s```
