### ISSUE TITLE
.netrc not found

### ISSUE THREAD

**Issue by Ksetrar** [khansaad1275/Termux-YTD#4]
Sir, I am getting this error even when i followed all steps btw the videos download though.

Image 
https://i.fiery.me/19S8e.jpg

**Comment by khansaad1275** [comment]
> Sir, I am getting this error even when i followed all steps btw the videos download though.
> 
> Image
> https://i.fiery.me/19S8e.jpg

It's not an Error, It's a warning, The tool will work fine.
